### ISSUE TITLE
Tags renamed

### ISSUE THREAD

**Issue by rnystrom** [rnystromtest/Githawk-Playground#32]
- [x] basic
- [x] checked
-  [ ] two spaces
-   [ ] three spaces
    - [x] indent
        - [x] two indents
- [X] capital

**Comment by rnystrom** [comment]
Testing

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Another test

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Another test

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
And again

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Something

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Test

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Hey sorry to bug sorry I’m on the road I’ll call me later tonight love 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystromtest** [comment]
Something

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystromtest** [comment]
Test

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystromtest** [comment]
Something

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystromtest** [comment]
Test

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystromtest** [comment]
Another

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
test #2
