### ISSUE TITLE
Testing styles

### ISSUE THREAD

**Issue by rnystromtest** [rnystromtest/Githawk-Playground#36]
This word is **bold** right @rnystrom? What about _italic_ and even _**italic bold**_?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@rnystrom first mention

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Some test @rnystrom 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
How do I repro this damn thing? @1234

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Repro! @rnystrom 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
